#%RAML 1.0 NamedExample
value:
  id: 3
  appointmentDate: 7/1/2021
  appointmentTime: 1:00pm
  vaccineType: Pfizer
  doseNumber: 2
  personalInfo:
    name: Jane Deer
    address: 789 Main Street, San Francisco, California 00000
    email: jane.deer@gmail.com
    phoneNumber: 222-333-4444
  price: 10.00
  paymentType: card
  paymentCard:
    cardNumber: 123456789
    expirationDate: 1/30
    securityCode: 123
