#%RAML 1.0 NamedExample
value:
  id: 1
  appointmentDate: 7/1/2021
  appointmentTime: 12:00pm
  vaccineType: Pfizer
  doseNumber: 1
  personalInfo:
    name: John Doe
    address: 123 Main Street, San Fransisco, California 00000
    email: john.doe@gmail.com
    phoneNumber: 732-732-7732
  price: 10.00
  paymentType: cash
