#%RAML 1.0 NamedExample
value:
  id: 2
  appointmentDate: 7/1/2021
  appointmentTime: 12:30pm
  vaccineType: Moderna
  doseNumber: 2
  personalInfo:
    name: Joe Smith
    address: 456 Main Street, San Fransisco, California 00000
    email: joe.smith@gmail.com
    phoneNumber: 777-777-7777
  price: 10.00
  paymentType: insurance
  insurance:
    providerName: CVS Health
    policyNumber: 123456789
